backend:
  name: github
  repo: ekinnyyy/versely-wallpapers

media_folder: /images
public_folder: /images

collections:
  - name: wallpapers
    label: Wallpapers
    files:
      - name: wallpaper_list
        label: Wallpaper Library
        file: /data/wallpapers.json
        format: json
        fields:
          - name: wallpapers
            label: Wallpaper Sets
            widget: list
            summary: "{{fields.title}}"
            add_to_top: true
            collapsed: auto
            fields:
              - name: title
                label: Title
                widget: string

              - name: category
                label: Category
                widget: string
                required: false

              - name: image_1
                label: Wallpaper 1
                widget: image

              - name: credit_name_1
                label: Credit Name 1
                widget: string
                required: false

              - name: credit_url_1
                label: Credit Link 1
                widget: string
                required: false

              - name: image_2
                label: Wallpaper 2
                widget: image
                required: false

              - name: credit_name_2
                label: Credit Name 2
                widget: string
                required: false

              - name: credit_url_2
                label: Credit Link 2
                widget: string
                required: false

              - name: image_3
                label: Wallpaper 3
                widget: image
                required: false

              - name: credit_name_3
                label: Credit Name 3
                widget: string
                required: false

              - name: credit_url_3
                label: Credit Link 3
                widget: string
                required: false

              - name: image_4
                label: Wallpaper 4
                widget: image
                required: false

              - name: credit_name_4
                label: Credit Name 4
                widget: string
                required: false

              - name: credit_url_4
                label: Credit Link 4
                widget: string
                required: false

              - name: image_5
                label: Wallpaper 5
                widget: image
                required: false

              - name: credit_name_5
                label: Credit Name 5
                widget: string
                required: false

              - name: credit_url_5
                label: Credit Link 5
                widget: string
                required: false
